name: scivision
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scipy
  - pandas
  - fsspec
  - pyyaml
  - requests
  - aiohttp
  - intake
  - intake-xarray
  - jupyter