name: Check catalogs
on:
  schedule:
    - cron:  '18 3 * * *'
  
jobs:
  check-catalogs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Scivision
        run: pip install -e .
      - name: Check data catalog
        run: python ./dev/check_datasets.py
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: check-datasets-report
          path: check_datasets.csv
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: catalog-checks-report-latest-release
          name: Catalog checks report
          commit: ${{ github.ref }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: check_datasets.js
