name: scivision
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
#     - uses: psf/black@stable
#       with:
#         options: "--check --verbose --line-length=79"
    - name:
        Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install scikit-image
        pip install tensorflow
        pip install xarray
    - name: Run Flake8
      run: |
        flake8
    - name: Run JSON validation script
      run: |
        python ./dev/validate_catalogs.py
    - name: Run tests
      run: |
        pip install -e .
        pip install pytest
        pytest
